import * as path from 'node:path';
import { readdir } from 'node:fs/promises';

const API_DIR = path.resolve(import.meta.dir, '../src/generated/api');
const ZOD_DIR = path.resolve(import.meta.dir, '../src/generated/zod');

async function generateBarrel(
  dir: string,
  fileNameFor: (folder: string) => string,
): Promise<number> {
  const entries = await readdir(dir, { withFileTypes: true });
  const folders = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  const exports = folders
    .map((folder) => `export * from "./${folder}/${fileNameFor(folder)}";`)
    .join('\n');
  const content = `// Generated by scripts/generate-barrel.ts — do not edit manually\n\n${exports}\n`;

  await Bun.write(path.join(dir, 'index.ts'), content);
  return folders.length;
}

const apiCount = await generateBarrel(API_DIR, (folder) => folder);
console.log(`Generated barrel with ${apiCount} exports`);

const zodCount = await generateBarrel(ZOD_DIR, (folder) => `${folder}.zod`);
console.log(`Generated zod barrel with ${zodCount} exports`);
