import * as path from 'node:path';
import { readdir } from 'node:fs/promises'; 

const API_DIR = path.resolve(import.meta.dir, '../src/generated/api');

const entries = await readdir(API_DIR, { withFileTypes: true });
const folders = entries
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

const exports = folders.map((folder) => `export * from "./${folder}/${folder}";`).join('\n');
const content = `// Generated by scripts/generate-barrel.ts — do not edit manually\n\n${exports}\n`;

await Bun.write(path.join(API_DIR, 'index.ts'), content);
console.log(`Generated barrel with ${folders.length} exports`);