#!/usr/bin/env tsx
/**
 * Materialises typed TS modules from the JSON contract artefacts the
 * backend emits (`dictionaries.json`, `enums.json`, `error-codes.json`).
 *
 * Runs after `kubb generate` so the generated SDK and the dictionaries
 * end up in the same output dir and ship together.
 *
 * Inputs (read from `../contracts/`, populated by the sync workflow or
 * a manual copy from profile-services):
 *   - dictionaries.json
 *   - enums.json
 *   - error-codes.json
 *
 * Outputs:
 *   - src/generated/dictionaries.ts
 *   - src/generated/enums.ts            (+ labelFor helper)
 *   - src/generated/error-codes.ts      (+ ErrorCode union type)
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, "..");
const CONTRACTS_DIR = resolve(PACKAGE_ROOT, "contracts");
const GENERATED_DIR = resolve(PACKAGE_ROOT, "src/generated");

interface LocalizedMessages {
  readonly en: string;
  readonly "pt-BR": string;
}

interface Dictionaries {
  readonly errors: Record<string, LocalizedMessages>;
  readonly enums: Record<string, Record<string, LocalizedMessages>>;
  readonly notifications: Record<
    string,
    { title: LocalizedMessages; body: LocalizedMessages; params: readonly string[] }
  >;
  readonly success: Record<string, LocalizedMessages>;
}

function readJson<T>(path: string): T {
  if (!existsSync(path)) {
    throw new Error(`[post-kubb] missing contract artefact: ${path}. Did the sync workflow run?`);
  }
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function ensureDir(path: string): void {
  if (!existsSync(path)) mkdirSync(path, { recursive: true });
}

function writeFile(path: string, content: string): void {
  ensureDir(dirname(path));
  writeFileSync(path, content, "utf8");
}

const BANNER = `// AUTO-GENERATED by scripts/post-kubb.ts — DO NOT EDIT MANUALLY.
// Source of truth lives in profile-services (\`bun run contracts:export\`).
// Re-run \`pnpm sdk:generate\` to refresh.
`;

function emitDictionaries(dict: Dictionaries): string {
  return `${BANNER}
export interface LocalizedMessages {
  readonly en: string;
  readonly 'pt-BR': string;
}

export type Locale = keyof LocalizedMessages;

export const DICTIONARIES = ${JSON.stringify(dict, null, 2)} as const;

export type Dictionaries = typeof DICTIONARIES;
`;
}

function emitEnums(
  prismaEnums: Record<string, readonly string[]>,
  enumLabels: Record<string, Record<string, LocalizedMessages>>,
): string {
  const enumTypeAliases = Object.entries(prismaEnums)
    .map(([name, values]) => {
      const union = values.map((v) => `'${v}'`).join(" | ");
      return `export type ${name} = ${union || "never"};`;
    })
    .join("\n");

  const enumConsts = Object.entries(prismaEnums)
    .map(([name, values]) => {
      const entries = values.map((v) => `  ${v}: '${v}'`).join(",\n");
      return `export const ${name} = {\n${entries},\n} as const satisfies Record<string, ${name}>;`;
    })
    .join("\n\n");

  return `${BANNER}
import { DICTIONARIES, type Locale } from './dictionaries';

${enumTypeAliases}

${enumConsts}

const ENUM_LABELS = ${JSON.stringify(enumLabels, null, 2)} as const;

export type EnumName = keyof typeof ENUM_LABELS;

/**
 * Resolves a localized human-readable label for an enum value.
 * Falls back to the raw value when no label is registered.
 */
export function labelFor<E extends EnumName>(
  enumName: E,
  value: string,
  locale: Locale = 'en',
): string {
  const dict = ENUM_LABELS[enumName] as
    | Record<string, { en: string; 'pt-BR': string }>
    | undefined;
  const entry = dict?.[value];
  if (!entry) return value;
  return entry[locale];
}

export { DICTIONARIES };
`;
}

function emitErrorCodes(codes: readonly string[]): string {
  const literals = codes.map((c) => `  '${c}'`).join(",\n");
  return `${BANNER}
export const ERROR_CODES = [
${literals},
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

const ERROR_CODE_SET = new Set<string>(ERROR_CODES);

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && ERROR_CODE_SET.has(value);
}
`;
}

function main(): void {
  ensureDir(GENERATED_DIR);

  const dict = readJson<Dictionaries>(resolve(CONTRACTS_DIR, "dictionaries.json"));
  const enums = readJson<Record<string, readonly string[]>>(resolve(CONTRACTS_DIR, "enums.json"));
  const errorCodes = readJson<readonly string[]>(resolve(CONTRACTS_DIR, "error-codes.json"));

  writeFile(resolve(GENERATED_DIR, "dictionaries.ts"), emitDictionaries(dict));
  writeFile(resolve(GENERATED_DIR, "enums.ts"), emitEnums(enums, dict.enums));
  writeFile(resolve(GENERATED_DIR, "error-codes.ts"), emitErrorCodes(errorCodes));

  console.log(
    `[post-kubb] wrote dictionaries (${Object.keys(dict.errors).length} errors), ` +
      `enums (${Object.keys(enums).length} prisma enums), ` +
      `error-codes (${errorCodes.length} codes)`,
  );
}

main();
