import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    // The Kubb-generated tree is regenerated by `pnpm sdk:generate`; we
    // only test the hand-written client + post-kubb modules.
    include: ["src/client/**/*.spec.ts", "src/client/**/*.test.ts"],
  },
});
