import type { IntentKey, IntentTokens } from './global.types';

export const intents: Record<IntentKey, IntentTokens> = {
  neutral: {
    light: {
      textColor: 'text-gray-50',
      mutedTextColor: 'text-gray-500',
      backgroundColor: 'bg-gray-800',
      backgroundColorHover: 'bg-gray-700',
      backgroundColorSubtle: 'bg-gray-100',
      backgroundColorSoft: 'bg-gray-100',
      textColorOnSoft: 'text-gray-700',
      borderColor: 'border-gray-300',
      borderColorFocus: 'focus:border-gray-900',
      iconColor: 'text-gray-500',
    },
    dark: {
      textColor: 'text-neutral-900',
      mutedTextColor: 'text-neutral-400',
      backgroundColor: 'bg-neutral-200',
      backgroundColorHover: 'bg-neutral-300',
      backgroundColorSubtle: 'bg-neutral-700',
      backgroundColorSoft: 'bg-neutral-700/50',
      textColorOnSoft: 'text-neutral-300',
      borderColor: 'border-neutral-700',
      borderColorFocus: 'focus:border-neutral-200',
      iconColor: 'text-neutral-400',
    },
  },
  accent: {
    light: {
      textColor: 'text-white',
      mutedTextColor: 'text-cyan-600',
      backgroundColor: 'bg-cyan-600',
      backgroundColorHover: 'bg-cyan-700',
      backgroundColorSubtle: 'bg-cyan-500/10',
      backgroundColorSoft: 'bg-cyan-50',
      textColorOnSoft: 'text-cyan-700',
      borderColor: 'border-cyan-500',
      borderColorFocus: 'focus:border-cyan-500',
      iconColor: 'text-cyan-600',
    },
    dark: {
      textColor: 'text-white',
      mutedTextColor: 'text-cyan-400',
      backgroundColor: 'bg-cyan-400',
      backgroundColorHover: 'bg-cyan-300',
      backgroundColorSubtle: 'bg-cyan-400/10',
      backgroundColorSoft: 'bg-cyan-900/30',
      textColorOnSoft: 'text-cyan-400',
      borderColor: 'border-cyan-400',
      borderColorFocus: 'focus:border-cyan-400',
      iconColor: 'text-cyan-400',
    },
  },
  danger: {
    light: {
      textColor: 'text-white',
      mutedTextColor: 'text-red-500',
      backgroundColor: 'bg-red-600',
      backgroundColorHover: 'bg-red-700',
      backgroundColorSubtle: 'bg-red-50',
      backgroundColorSoft: 'bg-red-50',
      textColorOnSoft: 'text-red-700',
      borderColor: 'border-red-500',
      borderColorFocus: 'focus:border-red-500',
      iconColor: 'text-red-600',
    },
    dark: {
      textColor: 'text-white',
      mutedTextColor: 'text-red-400',
      backgroundColor: 'bg-red-400',
      backgroundColorHover: 'bg-red-300',
      backgroundColorSubtle: 'bg-red-900/20',
      backgroundColorSoft: 'bg-red-900/30',
      textColorOnSoft: 'text-red-400',
      borderColor: 'border-red-400',
      borderColorFocus: 'focus:border-red-400',
      iconColor: 'text-red-400',
    },
  },
  success: {
    light: {
      textColor: 'text-white',
      mutedTextColor: 'text-emerald-600',
      backgroundColor: 'bg-emerald-600',
      backgroundColorHover: 'bg-emerald-700',
      backgroundColorSubtle: 'bg-emerald-500/10',
      backgroundColorSoft: 'bg-emerald-50',
      textColorOnSoft: 'text-emerald-700',
      borderColor: 'border-emerald-500',
      borderColorFocus: 'focus:border-emerald-500',
      iconColor: 'text-emerald-600',
    },
    dark: {
      textColor: 'text-white',
      mutedTextColor: 'text-emerald-400',
      backgroundColor: 'bg-emerald-400',
      backgroundColorHover: 'bg-emerald-300',
      backgroundColorSubtle: 'bg-emerald-400/10',
      backgroundColorSoft: 'bg-emerald-900/30',
      textColorOnSoft: 'text-emerald-400',
      borderColor: 'border-emerald-400',
      borderColorFocus: 'focus:border-emerald-400',
      iconColor: 'text-emerald-400',
    },
  },
  warning: {
    light: {
      textColor: 'text-white',
      mutedTextColor: 'text-amber-600',
      backgroundColor: 'bg-amber-500',
      backgroundColorHover: 'bg-amber-600',
      backgroundColorSubtle: 'bg-amber-500/10',
      backgroundColorSoft: 'bg-amber-50',
      textColorOnSoft: 'text-amber-700',
      borderColor: 'border-amber-500',
      borderColorFocus: 'focus:border-amber-500',
      iconColor: 'text-amber-600',
    },
    dark: {
      textColor: 'text-white',
      mutedTextColor: 'text-amber-400',
      backgroundColor: 'bg-amber-400',
      backgroundColorHover: 'bg-amber-300',
      backgroundColorSubtle: 'bg-amber-400/10',
      backgroundColorSoft: 'bg-amber-900/30',
      textColorOnSoft: 'text-amber-400',
      borderColor: 'border-amber-400',
      borderColorFocus: 'focus:border-amber-400',
      iconColor: 'text-amber-400',
    },
  },
  info: {
    light: {
      textColor: 'text-white',
      mutedTextColor: 'text-blue-600',
      backgroundColor: 'bg-blue-600',
      backgroundColorHover: 'bg-blue-700',
      backgroundColorSubtle: 'bg-blue-500/10',
      backgroundColorSoft: 'bg-blue-50',
      textColorOnSoft: 'text-blue-700',
      borderColor: 'border-blue-500',
      borderColorFocus: 'focus:border-blue-500',
      iconColor: 'text-blue-600',
    },
    dark: {
      textColor: 'text-white',
      mutedTextColor: 'text-blue-400',
      backgroundColor: 'bg-blue-400',
      backgroundColorHover: 'bg-blue-300',
      backgroundColorSubtle: 'bg-blue-400/10',
      backgroundColorSoft: 'bg-blue-900/30',
      textColorOnSoft: 'text-blue-400',
      borderColor: 'border-blue-400',
      borderColorFocus: 'focus:border-blue-400',
      iconColor: 'text-blue-400',
    },
  },
};
