#!/usr/bin/env bun

// Merges /tmp/i18n-bucket-{1..4}-output.json into:
//   - packages/i18n/src/dictionaries/pt-BR.json   (in-place)
//   - packages/i18n/src/dictionaries/en.json      (in-place)
//   - scripts/i18n-pending-sweep.json             (key → source locations
//                                                   index for the upcoming
//                                                   hardcoded-string sweep)
//
// One-shot helper — not registered in .precommit.yaml. Run with:
//   bun scripts/_merge-i18n-proposals.ts

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const PT_PATH = join(ROOT, 'packages/i18n/src/dictionaries/pt-BR.json');
const EN_PATH = join(ROOT, 'packages/i18n/src/dictionaries/en.json');
const SWEEP_PATH = join(ROOT, 'scripts/i18n-pending-sweep.json');

interface SourceEntry {
  file: string;
  line: number;
  col: number;
  value: string;
  rule: string;
  context: string;
}

interface Proposal {
  key: string;
  ptBR?: string;
  en?: string;
  sourceEntries: SourceEntry[];
}

interface BucketOutput {
  bucket: number;
  proposals: Proposal[];
}

type JsonNode = string | { [k: string]: JsonNode };

function loadDict(path: string): { [k: string]: JsonNode } {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function getLeaf(dict: { [k: string]: JsonNode }, dotPath: string): string | null {
  const segs = dotPath.split('.');
  let cur: JsonNode = dict;
  for (const s of segs) {
    if (typeof cur !== 'object' || cur === null) return null;
    cur = cur[s];
    if (cur === undefined) return null;
  }
  return typeof cur === 'string' ? cur : null;
}

function setLeaf(
  dict: { [k: string]: JsonNode },
  dotPath: string,
  value: string,
  collisions: string[],
): void {
  const segs = dotPath.split('.');
  const last = segs.pop()!;
  let cur: { [k: string]: JsonNode } = dict;
  for (const s of segs) {
    const next = cur[s];
    if (next === undefined) {
      cur[s] = {};
      cur = cur[s] as { [k: string]: JsonNode };
    } else if (typeof next === 'string') {
      collisions.push(`${dotPath}: parent segment '${s}' is a string leaf`);
      return;
    } else if (typeof next === 'object') {
      cur = next as { [k: string]: JsonNode };
    } else {
      collisions.push(`${dotPath}: parent segment '${s}' is not object/string`);
      return;
    }
  }
  const existing = cur[last];
  if (typeof existing === 'object') {
    collisions.push(`${dotPath}: target is an existing object (subtree clash)`);
    return;
  }
  if (typeof existing === 'string' && existing !== value) {
    collisions.push(
      `${dotPath}: overwriting existing leaf "${existing}" -> "${value}"`,
    );
  }
  cur[last] = value;
}

const buckets: BucketOutput[] = [];
for (const i of [1, 2, 3, 4]) {
  const raw = readFileSync(`/tmp/i18n-bucket-${i}-output.json`, 'utf8');
  buckets.push(JSON.parse(raw));
}

const pt = loadDict(PT_PATH);
const en = loadDict(EN_PATH);

const ptCollisions: string[] = [];
const enCollisions: string[] = [];

let newKeys = 0;
let reusedKeys = 0;
let updatedExistingKeys = 0;

const sweepEntries: { key: string; sources: SourceEntry[] }[] = [];

for (const bucket of buckets) {
  for (const p of bucket.proposals) {
    const reused = !p.ptBR && !p.en;
    if (reused) {
      reusedKeys++;
    } else {
      const existed = getLeaf(pt, p.key) !== null;
      if (existed) updatedExistingKeys++;
      else newKeys++;
      setLeaf(pt, p.key, p.ptBR ?? '', ptCollisions);
      setLeaf(en, p.key, p.en ?? '', enCollisions);
    }
    sweepEntries.push({ key: p.key, sources: p.sourceEntries });
  }
}

if (ptCollisions.length || enCollisions.length) {
  console.error('Collisions detected — aborting:');
  for (const c of [...ptCollisions, ...enCollisions]) console.error(`  ${c}`);
  process.exit(1);
}

writeFileSync(PT_PATH, `${JSON.stringify(pt, null, 2)}\n`);
writeFileSync(EN_PATH, `${JSON.stringify(en, null, 2)}\n`);

const sweepFile = {
  note:
    'Maps each newly-introduced i18n key to the source-code locations whose hardcoded literal should be replaced with `t("<key>")`. Generated by 4 parallel agents from the check-i18n-hardcoded baseline; keys are exempted from i18n-orphans until the sweep replaces the literals. Refresh by re-running the 4-agent flow + bun scripts/_merge-i18n-proposals.ts.',
  count: sweepEntries.length,
  entries: sweepEntries.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0)),
};
writeFileSync(SWEEP_PATH, `${JSON.stringify(sweepFile, null, 2)}\n`);

console.log(`Merge complete:
  new keys:               ${newKeys}
  reused existing keys:   ${reusedKeys}
  updated existing keys:  ${updatedExistingKeys}
  sweep mapping entries:  ${sweepEntries.length}
  pt-BR.json + en.json:   rewritten
  scripts/i18n-pending-sweep.json: created`);
